import type { ExperienceKind, LifeCategory } from "../generated/prisma/enums";

/*
 * Курируемый каталог (ADR-006).
 *
 * Главное правило этого файла — пропорция. Продукт не про афишу города:
 * событий здесь меньшинство, потому что событие требует денег, погоды,
 * билета и правильного города, а неделя случается у человека всегда.
 * Большая часть каталога — вызовы себе и тихие ритуалы: они доступны
 * в любую неделю, в любом городе и чаще всего бесплатны.
 *
 * Тон описаний — по 14-brand-and-copy: спокойно, конкретно, без пафоса
 * и без языка продуктивности. Описание отвечает на «что именно делать»,
 * а не уговаривает.
 *
 * slug — стабильный ключ идемпотентности, лежит в metadata. Менять нельзя:
 * по нему сид находит уже созданную строку и обновляет её вместо дубля.
 */

export type CatalogItem = {
  slug: string;
  kind: ExperienceKind;
  category: LifeCategory;
  title: string;
  description: string;
  /** Минуты. Ориентир для человека, не обязательство. */
  durationMin?: number;
  /** RSD. 0 — бесплатно. Не указано — зависит от того, как сделаешь. */
  price?: number;
  /** Только для EVENT: остальное не привязано к городу и живёт везде. */
  city?: string;
  location?: string;
  distanceKm?: number;
};

/* ─────────────────── EVENT — привязано к месту и дате ─────────────────── */

const EVENTS: CatalogItem[] = [
  {
    slug: "bg-ada-sunrise-kayak",
    kind: "EVENT",
    category: "NATURE",
    title: "Каякинг на Аде на рассвете",
    description: "Группа до 6 человек, опыт не нужен. Снаряжение включено.",
    city: "Белград",
    location: "Ада Циганлија",
    durationMin: 120,
    price: 2200,
    distanceKm: 7,
  },
  {
    slug: "bg-kalemegdan-night-walk",
    kind: "EVENT",
    category: "DISCOVERY",
    title: "Ночная прогулка по Калемегдану",
    description: "Крепость, слияние Савы и Дуная, город с высоты. Бесплатно.",
    city: "Белград",
    location: "Калемегдан",
    durationMin: 90,
    price: 0,
    distanceKm: 3,
  },
  {
    slug: "bg-pottery-workshop",
    kind: "EVENT",
    category: "JOY",
    title: "Гончарная мастерская для новичков",
    description: "Мастер оставит работу на обжиг. Можно прийти вдвоём.",
    city: "Белград",
    location: "Дорћол",
    durationMin: 150,
    price: 3500,
    distanceKm: 4,
  },
  {
    slug: "bg-kolarac-organ",
    kind: "EVENT",
    category: "CULTURE",
    title: "Органный вечер в Коларце",
    description: "Классическая программа при свечах. Билеты обычно есть.",
    city: "Белград",
    location: "Задужбина Илије М. Коларца",
    durationMin: 120,
    price: 1800,
    distanceKm: 5,
  },
  {
    slug: "bg-climbing-intro",
    kind: "EVENT",
    category: "CHALLENGE",
    title: "Скалодром: первое занятие",
    description: "Инструктор и снаряжение включены. Можно одному.",
    city: "Белград",
    location: "Вождовац",
    durationMin: 90,
    price: 1500,
    distanceKm: 8,
  },
  {
    slug: "bg-skydive-tandem",
    kind: "EVENT",
    category: "CHALLENGE",
    title: "Прыжок с парашютом в тандеме",
    description: "Инструктаж час, свободное падение сорок секунд. Записываться заранее.",
    city: "Белград",
    location: "Аеродром Лисичји Јарак",
    durationMin: 240,
    price: 18000,
    distanceKm: 22,
  },
  {
    slug: "bg-dance-first-class",
    kind: "EVENT",
    category: "MOVEMENT",
    title: "Первое занятие сальсой",
    description: "Приходят без пары и без опыта — партнёров меняют по кругу.",
    city: "Белград",
    location: "Врачар",
    durationMin: 90,
    price: 1200,
    distanceKm: 4,
  },
  {
    slug: "bg-flea-market-dawn",
    kind: "EVENT",
    category: "DISCOVERY",
    title: "Блошиный рынок на рассвете",
    description: "Самое интересное разбирают до восьми утра. Наличные.",
    city: "Белград",
    location: "Бувљак, Земун",
    durationMin: 120,
    price: 0,
    distanceKm: 11,
  },
  {
    slug: "ns-petrovaradin-sunrise",
    kind: "EVENT",
    category: "NATURE",
    title: "Рассвет на Петроварадинской крепости",
    description: "Дунай в тумане и пустой город внизу. Нужен ранний подъём.",
    city: "Нови-Сад",
    location: "Петроварадинска тврђава",
    durationMin: 120,
    price: 0,
    distanceKm: 4,
  },
  {
    slug: "ns-danube-cycling",
    kind: "EVENT",
    category: "MOVEMENT",
    title: "Велодень вдоль Дуная",
    description: "Ровный маршрут по набережной, прокат рядом.",
    city: "Нови-Сад",
    location: "Штранд",
    durationMin: 180,
    price: 900,
    distanceKm: 5,
  },
  {
    slug: "ns-shared-dinner",
    kind: "EVENT",
    category: "CONNECTION",
    title: "Ужин за общим столом",
    description: "Формат знакомства: восемь человек, домашняя кухня Воеводины.",
    city: "Нови-Сад",
    location: "Центр",
    durationMin: 150,
    price: 2600,
    distanceKm: 2,
  },
  {
    slug: "ns-fruska-gora-hike",
    kind: "EVENT",
    category: "NATURE",
    title: "Пеший день на Фрушка-Горе",
    description: "Маркированная тропа, монастыри по дороге. Автобус от центра.",
    city: "Нови-Сад",
    location: "Фрушка гора",
    durationMin: 360,
    price: 400,
    distanceKm: 18,
  },
  {
    slug: "bg-blood-donation",
    kind: "EVENT",
    category: "CONTRIBUTION",
    title: "Сдать кровь",
    description: "Полчаса, паспорт, лёгкий завтрак заранее. Записи не нужно.",
    city: "Белград",
    location: "Институт за трансфузију крви",
    durationMin: 60,
    price: 0,
    distanceKm: 5,
  },
  {
    slug: "bg-shelter-volunteering",
    kind: "EVENT",
    category: "CONTRIBUTION",
    title: "День в приюте для собак",
    description: "Выгул и уборка. Приходят и на один раз, без обязательств.",
    city: "Белград",
    location: "Прихватилиште, Овча",
    durationMin: 240,
    price: 0,
    distanceKm: 17,
  },
  {
    slug: "bg-thermal-bath",
    kind: "EVENT",
    category: "REST",
    title: "День на термальных источниках",
    description: "Горячая вода под открытым небом. Работают круглый год.",
    city: "Белград",
    location: "Бања Ковиљача",
    durationMin: 300,
    price: 1400,
    distanceKm: 130,
  },
  {
    slug: "bg-open-air-cinema",
    kind: "EVENT",
    category: "CULTURE",
    title: "Кино под открытым небом",
    description: "Плед берут с собой. Начало после заката.",
    city: "Белград",
    location: "Двориште Кинотеке",
    durationMin: 150,
    price: 600,
    distanceKm: 3,
  },
];

/* ─────────── CHALLENGE — вызов себе, живёт вечно и почти всегда бесплатен ─────────── */

const CHALLENGES: CatalogItem[] = [
  {
    slug: "ch-ask-someone-out",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Позвать на свидание того, о ком думаешь",
    description: "Одно сообщение. Не идеальное — просто отправленное.",
    durationMin: 5,
    price: 0,
  },
  {
    slug: "ch-call-after-year",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Позвонить тому, с кем не говорил год",
    description: "Без повода и без объяснений, почему так долго молчал.",
    durationMin: 20,
    price: 0,
  },
  {
    slug: "ch-say-the-thing",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Сказать вслух то, что откладывал",
    description: "Тому самому человеку. Можно коротко, можно неловко.",
    durationMin: 15,
    price: 0,
  },
  {
    slug: "ch-apologize-first",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Извиниться первым",
    description: "Без «но» во второй половине фразы.",
    durationMin: 10,
    price: 0,
  },
  {
    slug: "ch-thank-a-parent",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Сказать родителю, за что ты ему благодарен",
    description: "Конкретно: не «за всё», а за один случай, который помнишь.",
    durationMin: 20,
    price: 0,
  },
  {
    slug: "ch-talk-to-stranger",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Заговорить первым с незнакомым человеком",
    description: "В очереди, в лифте, у соседнего столика. Одна фраза считается.",
    durationMin: 5,
    price: 0,
  },
  {
    slug: "ch-ask-for-help",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Попросить о помощи",
    description: "То, что давно тянешь один, потому что неудобно просить.",
    durationMin: 15,
    price: 0,
  },
  {
    slug: "ch-say-no",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Сказать «нет» тому, чему всегда говоришь «да»",
    description: "Один раз, без развёрнутого оправдания.",
    durationMin: 5,
    price: 0,
  },
  {
    slug: "ch-dinner-alone",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Поужинать одному в ресторане",
    description: "Без телефона на столе. Первые десять минут самые странные.",
    durationMin: 90,
    price: 1500,
  },
  {
    slug: "ch-sing-in-public",
    kind: "CHALLENGE",
    category: "JOY",
    title: "Спеть при людях",
    description: "Караоке, двор, компания друзей. Петь хорошо не требуется.",
    durationMin: 60,
    price: 0,
  },
  {
    slug: "ch-cold-water",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Зайти в холодную воду",
    description: "Река, море, душ. Три минуты, дышать медленно.",
    durationMin: 15,
    price: 0,
  },
  {
    slug: "ch-childhood-fear",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Сделать то, чего боялся с детства",
    description: "Высота, вода, темнота, сцена — ты знаешь, что именно.",
    durationMin: 60,
    price: 0,
  },
  {
    slug: "ch-speak-in-front",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Выступить перед людьми",
    description: "Тост, доклад, открытый микрофон. Пять минут хватит.",
    durationMin: 30,
    price: 0,
  },
  {
    slug: "ch-solo-overnight",
    kind: "CHALLENGE",
    category: "NATURE",
    title: "Ночёвка на природе в одиночку",
    description: "Одна ночь, палатка, никакой связи. Тишина громче, чем ожидаешь.",
    durationMin: 900,
    price: 0,
  },
  {
    slug: "ch-unknown-town",
    kind: "CHALLENGE",
    category: "DISCOVERY",
    title: "Уехать в город, о котором ничего не знаешь",
    description: "Билет на ближайший автобус, никакого плана и ни одной статьи заранее.",
    durationMin: 480,
    price: 1200,
  },
  {
    slug: "ch-day-without-phone",
    kind: "CHALLENGE",
    category: "REST",
    title: "Прожить день без телефона",
    description: "С утра до вечера. Договорись с близкими заранее, чтобы не искали.",
    durationMin: 720,
    price: 0,
  },
  {
    slug: "ch-hitchhike",
    kind: "CHALLENGE",
    category: "DISCOVERY",
    title: "Проехать часть пути автостопом",
    description: "Хотя бы один перегон. Днём, по трассе, где есть где встать.",
    durationMin: 240,
    price: 0,
  },
  {
    slug: "ch-learn-and-show",
    kind: "CHALLENGE",
    category: "DISCOVERY",
    title: "Научиться чему-то за неделю и показать",
    description: "Одна песня, один фокус, одно блюдо. Показать живому человеку.",
    durationMin: 300,
    price: 0,
  },
  {
    slug: "ch-cook-for-parent",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Приготовить ужин тому, кто кормил тебя",
    description: "Родителю, бабушке, старшему другу. Ты готовишь, они сидят.",
    durationMin: 180,
    price: 1500,
  },
  {
    slug: "ch-blind-date",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Сходить на свидание вслепую",
    description: "Пусть друг выберет за тебя. Кофе, час, без обязательств.",
    durationMin: 90,
    price: 800,
  },
  {
    slug: "ch-fifty-km",
    kind: "CHALLENGE",
    category: "MOVEMENT",
    title: "Проехать пятьдесят километров на велосипеде",
    description: "За один день, с остановками. Вода и насос с собой.",
    durationMin: 300,
    price: 0,
  },
  {
    slug: "ch-walk-till-dark",
    kind: "CHALLENGE",
    category: "MOVEMENT",
    title: "Идти пешком, пока не стемнеет",
    description: "Выбрать направление и не сворачивать к транспорту.",
    durationMin: 300,
    price: 0,
  },
  {
    slug: "ch-dawn-alone",
    kind: "CHALLENGE",
    category: "NATURE",
    title: "Встать до рассвета и встретить его",
    description: "Крыша, холм, окно. Один, без музыки в наушниках.",
    durationMin: 90,
    price: 0,
  },
  {
    slug: "ch-paraglide",
    kind: "CHALLENGE",
    category: "CHALLENGE",
    title: "Полетать на параплане с инструктором",
    description: "Тандем, зависит от ветра. Планировать с запасом по погоде.",
    durationMin: 180,
    price: 9000,
  },
  {
    slug: "ch-dance-sober",
    kind: "CHALLENGE",
    category: "JOY",
    title: "Танцевать трезвым",
    description: "На вечеринке, дома, где угодно — но не выпив для храбрости.",
    durationMin: 60,
    price: 0,
  },
  {
    slug: "ch-give-to-stranger",
    kind: "CHALLENGE",
    category: "CONTRIBUTION",
    title: "Помочь незнакомцу и уйти не назвавшись",
    description: "Не рассказывать об этом никому неделю.",
    durationMin: 30,
    price: 0,
  },
  {
    slug: "ch-teach-someone",
    kind: "CHALLENGE",
    category: "CONTRIBUTION",
    title: "Научить кого-то тому, что умеешь",
    description: "Один вечер, один человек. То, что тебе кажется очевидным.",
    durationMin: 120,
    price: 0,
  },
  {
    slug: "ch-pay-it-forward",
    kind: "CHALLENGE",
    category: "CONTRIBUTION",
    title: "Оплатить кофе следующему в очереди",
    description: "И не оборачиваться посмотреть на реакцию.",
    durationMin: 10,
    price: 300,
  },
  {
    slug: "ch-clean-favorite-place",
    kind: "CHALLENGE",
    category: "CONTRIBUTION",
    title: "Убрать мусор в месте, которое любишь",
    description: "Пакет, перчатки, час. Берег, парк, двор.",
    durationMin: 60,
    price: 0,
  },
  {
    slug: "ch-confess-feelings",
    kind: "CHALLENGE",
    category: "CONNECTION",
    title: "Признаться в чувствах",
    description: "Без расчёта на ответ. Важно сказать, а не услышать.",
    durationMin: 20,
    price: 0,
  },
  {
    slug: "ch-first-time-solo-trip",
    kind: "CHALLENGE",
    category: "DISCOVERY",
    title: "Уехать на выходные одному",
    description: "Две ночи, никакой компании, маршрут придумываешь на месте.",
    durationMin: 1440,
    price: 6000,
  },
  {
    slug: "ch-draw-a-person",
    kind: "CHALLENGE",
    category: "JOY",
    title: "Нарисовать человека с натуры",
    description: "Попросить кого-то посидеть двадцать минут. Похоже не обязательно.",
    durationMin: 40,
    price: 0,
  },
];

/* ─────────── RITUAL — тихое и домашнее, доступно в любую неделю ─────────── */

const RITUALS: CatalogItem[] = [
  {
    slug: "ri-postponed-film",
    kind: "RITUAL",
    category: "CULTURE",
    title: "Посмотреть фильм, который откладывал годами",
    description: "Тот самый, из списка. Целиком, без телефона и без паузы.",
    durationMin: 120,
    price: 0,
  },
  {
    slug: "ri-book-in-one-evening",
    kind: "RITUAL",
    category: "CULTURE",
    title: "Прочитать книгу за один вечер",
    description: "Небольшую, до двухсот страниц. От первой до последней.",
    durationMin: 240,
    price: 0,
  },
  {
    slug: "ri-album-whole",
    kind: "RITUAL",
    category: "CULTURE",
    title: "Послушать альбом целиком",
    description: "От начала до конца, в наушниках, ничего не делая параллельно.",
    durationMin: 45,
    price: 0,
  },
  {
    slug: "ri-childhood-film",
    kind: "RITUAL",
    category: "JOY",
    title: "Пересмотреть фильм из детства",
    description: "Тот, что знал наизусть. Половину ты помнил неправильно.",
    durationMin: 100,
    price: 0,
  },
  {
    slug: "ri-letter-to-future-self",
    kind: "RITUAL",
    category: "DISCOVERY",
    title: "Написать письмо себе через год",
    description: "От руки, запечатать, положить туда, где найдёшь не скоро.",
    durationMin: 40,
    price: 0,
  },
  {
    slug: "ri-grandmother-recipe",
    kind: "RITUAL",
    category: "CONNECTION",
    title: "Приготовить блюдо по семейному рецепту",
    description: "Позвонить и записать его, пока есть у кого спросить.",
    durationMin: 150,
    price: 1200,
  },
  {
    slug: "ri-old-photos",
    kind: "RITUAL",
    category: "CONNECTION",
    title: "Разобрать старые фотографии",
    description: "Коробка, папка на диске, старый телефон. Вслух с кем-нибудь — лучше.",
    durationMin: 90,
    price: 0,
  },
  {
    slug: "ri-call-grandparent",
    kind: "RITUAL",
    category: "CONNECTION",
    title: "Позвонить бабушке и просто послушать",
    description: "Не отчитываться о делах. Спросить про её молодость.",
    durationMin: 40,
    price: 0,
  },
  {
    slug: "ri-candlelight-evening",
    kind: "RITUAL",
    category: "REST",
    title: "Провести вечер при свечах",
    description: "Свет выключен, экраны тоже. Три часа до сна.",
    durationMin: 180,
    price: 0,
  },
  {
    slug: "ri-sleep-without-alarm",
    kind: "RITUAL",
    category: "REST",
    title: "Выспаться без будильника",
    description: "Один день, когда некуда вставать. Договориться об этом заранее.",
    durationMin: 600,
    price: 0,
  },
  {
    slug: "ri-bath-no-phone",
    kind: "RITUAL",
    category: "REST",
    title: "Час в ванне без телефона",
    description: "Горячая вода, книга или тишина. Телефон в другой комнате.",
    durationMin: 60,
    price: 0,
  },
  {
    slug: "ri-morning-pages",
    kind: "RITUAL",
    category: "DISCOVERY",
    title: "Три страницы от руки утром",
    description: "Всё, что в голове, без правки и без цели. Никто не прочитает.",
    durationMin: 30,
    price: 0,
  },
  {
    slug: "ri-playlist-seventeen",
    kind: "RITUAL",
    category: "JOY",
    title: "Собрать плейлист из песен своих семнадцати",
    description: "Двадцать треков. Слушать вечером, целиком.",
    durationMin: 60,
    price: 0,
  },
  {
    slug: "ri-list-of-done",
    kind: "RITUAL",
    category: "DISCOVERY",
    title: "Написать список того, что уже сбылось",
    description: "То, чего когда-то очень хотел и что давно считаешь обычным.",
    durationMin: 30,
    price: 0,
  },
  {
    slug: "ri-breakfast-in-silence",
    kind: "RITUAL",
    category: "REST",
    title: "Позавтракать в тишине у окна",
    description: "Без ленты, без музыки, без разговоров. Двадцать минут.",
    durationMin: 20,
    price: 0,
  },
  {
    slug: "ri-breakfast-for-someone",
    kind: "RITUAL",
    category: "CONNECTION",
    title: "Приготовить завтрак тому, с кем живёшь",
    description: "Встать раньше. Ничего не говорить заранее.",
    durationMin: 45,
    price: 0,
  },
  {
    slug: "ri-declutter-and-give",
    kind: "RITUAL",
    category: "CONTRIBUTION",
    title: "Разобрать шкаф и отдать то, что не носишь",
    description: "Одна сумка. Отнести в тот же день, пока не передумал.",
    durationMin: 120,
    price: 0,
  },
  {
    slug: "ri-old-neighbourhood",
    kind: "RITUAL",
    category: "DISCOVERY",
    title: "Съездить в свой старый двор",
    description: "Тот, где вырос. Постоять, ничего не фотографируя.",
    durationMin: 120,
    price: 0,
  },
  {
    slug: "ri-board-game-evening",
    kind: "RITUAL",
    category: "JOY",
    title: "Вечер за настольной игрой",
    description: "Двое и больше, телефоны в другой комнате.",
    durationMin: 150,
    price: 0,
  },
  {
    slug: "ri-map-of-good-places",
    kind: "RITUAL",
    category: "DISCOVERY",
    title: "Составить карту мест, где было хорошо",
    description: "От руки или в заметках. Против каждого — одна строчка почему.",
    durationMin: 45,
    price: 0,
  },
  {
    slug: "ri-long-bath-of-a-walk",
    kind: "RITUAL",
    category: "NATURE",
    title: "Гулять час без маршрута",
    description: "Выйти из дома и сворачивать туда, где не был. Без наушников.",
    durationMin: 60,
    price: 0,
  },
  {
    slug: "ri-plant-something",
    kind: "RITUAL",
    category: "NATURE",
    title: "Посадить что-нибудь",
    description: "Дерево во дворе или зелень на подоконнике. Поливать потом.",
    durationMin: 60,
    price: 500,
  },
  {
    slug: "ri-stretch-before-sleep",
    kind: "RITUAL",
    category: "MOVEMENT",
    title: "Двадцать минут растяжки перед сном",
    description: "На полу, медленно. Тело помнит, что вы давно не виделись.",
    durationMin: 20,
    price: 0,
  },
  {
    slug: "ri-cook-something-new",
    kind: "RITUAL",
    category: "JOY",
    title: "Приготовить блюдо, которого никогда не готовил",
    description: "Кухня страны, где не был. Купить незнакомую специю.",
    durationMin: 120,
    price: 1000,
  },
  {
    slug: "ri-voice-note-to-self",
    kind: "RITUAL",
    category: "DISCOVERY",
    title: "Записать голосовое самому себе",
    description: "Что сейчас важно и чего боишься. Послушать через полгода.",
    durationMin: 15,
    price: 0,
  },
  {
    slug: "ri-museum-one-room",
    kind: "RITUAL",
    category: "CULTURE",
    title: "Прийти в музей ради одного зала",
    description: "Не обходить всё. Сесть напротив одной вещи на двадцать минут.",
    durationMin: 60,
    price: 500,
  },
];

/** Полный каталог. Порядок внутри файла — по типам, не по важности. */
export const CATALOG: CatalogItem[] = [...EVENTS, ...CHALLENGES, ...RITUALS];
